spring.application.name=detector-de-golpes
spring.config.import=optional:file:.env[.properties]
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent

#o unico que ta funcionando é o 3.5 flash lite(meia hora tentando)